#server:
#  port: 8090

spring:
  aop:
    auto: true
    proxy-target-class: true

dubboconfig:
  applicationconfig:
    name: @applicationConfig.name@
    logger: @applicationConfig.logger@
    owner: @applicationConfig.owner@
    organization: @applicationConfig.organization@
  registryconfig:
    protocol: @registryConfig.protocol@
    address: @registryConfig.address@
    client: @registryConfig.client@

  providerconfig:

    threads: @providerConfig.threads@
    threadpool: @providerConfig.threadpool@
    timeout: @providerConfig.timeout@
    version: @providerConfig.version@
    filter: @providerConfig.filter@
    retries: @providerConfig.retries@

  consumerconfig:
    loadbalance: @consumerConfig.loadbalance@
    cluster: @consumerConfig.cluster@
    version: @consumerConfig.version@
    #mock: @mock@
  protocolconfig:
    name: @protocolConfig.name@
    port: @protocolConfig.port@


druid:
  type: com.alibaba.druid.pool.DruidDataSource
  origin:
    master:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://192.168.0.12:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 12
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 2
      max-active: 50
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
    slave:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://192.168.0.12:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 12
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 2
      max-active: 50
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20


mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.qhbd.entity  # 注意：对应实体类的路径
  configuration:
    aggressive-lazy-loading: false #按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
    default-executor-type: REUSE #对于批量更新操作缓存SQL以提高性能
    default-statement-timeout: 25000

